general.import = [
    "~/.config/alacritty/solarized_dark.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.66"
TERM="xterm-256color"

[font]
size = 6.0

[font.normal]
family = "xos4 Terminus"
style = "Regular"

[window.padding]
x = 6
y = 6

[window.dimensions]
columns = 80
lines = 24
